root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2019

env:
  browser: true
  es2017: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

plugins:
  - svelte3
  - '@typescript-eslint'
  - import
  - unused-imports

settings:
  svelte3/typescript: true

overrides:
  - files: ['*.svelte']
    processor: svelte3/svelte3

rules:
  # Imports.
  '@typescript-eslint/no-unused-vars': off
  import/order:
    - warn
    - groups: [builtin, external, type, parent, sibling, index]
  import/no-unused-modules: warn
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
  unused-imports/no-unused-imports: error
