root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2019

env:
  browser: true
  es2017: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

plugins:
  - svelte3
  - '@typescript-eslint'
  - import
  - simple-import-sort
  - unused-imports

settings:
  svelte3/typescript: true
  import/resolver:
    typescript: {}

overrides:
  - files: ['*.svelte']
    processor: svelte3/svelte3
    rules:
      import/first: off
      import/no-duplicates: off
      import/no-unused-modules: off

rules:
  # Imports.
  '@typescript-eslint/no-unused-vars': off
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/no-unresolved: off
  import/no-unused-modules: warn
  simple-import-sort/exports: error
  simple-import-sort/imports: error
  unused-imports/no-unused-imports: error
