import { generateCstDts } from 'chevrotain'
import { writeFileSync } from 'fs'
import { basename, resolve } from 'path'

import { productions } from '../src/parse'

const filename = basename(import.meta.url)

const PREFIX_COMMENT = `
  // Code generated by "${filename}"; DO NOT EDIT.
`.trimStart()

const dtsString = PREFIX_COMMENT + generateCstDts(productions)
const dtsPath = resolve('src', 'cst.gen.d.ts')
writeFileSync(dtsPath, dtsString)
