import { generateCstDts } from 'chevrotain'
import { writeFileSync } from 'fs'
import { basename, resolve } from 'path'

// ts-node seems bugged; need to explicitly set ".js" extension.
import { productions } from '../src/lib/formula/parse.js'

const filename = basename(import.meta.url)

const PREFIX_COMMENT = `
  // Code generated by "${filename}"; DO NOT EDIT.
`.trimStart()

const dtsString = PREFIX_COMMENT + generateCstDts(productions)
const dtsPath = resolve('src/lib/formula', 'cst.gen.d.ts')
writeFileSync(dtsPath, dtsString)
